# Introduccion a la programacion para la ciencia de datos

La ciencia de datos permite hacer innumerables aplicaciones en su mayoría basadas en estadistica, programacion, visualizaciones y modelos que representan sistemas dinamicos, y para ello tendremos que plasmar dicha realidad en datos, y porteriormente darle un sentido matematico, a continuacion veremos el modulo `Numpy` el cual es una herramienta que nos permite hacer eso

# Modulo Numpy

<img src = "./images/numpy_logo.png" height = "280" width = "280">

Numpy es un paquete fundamental para el trabajo científico en python:

* Contiene Funciones, módulos, clases y cierto tipo especial de datos. 
* Permite el manejo de Arrays Multidimensionales. 
* Contiene Funciones sofisticadas y optimizadas.
* Contiene un paquete de álgebra lineal y permite hacer cálculos estadísticos, ajustes, interpolación entre otras.


> El tipo de dato mas importante en numpy es el **array**. El array es un tipo de dato, formado a partir de otro tipo de datos mas sencillos y que estan ordenados en una secuencia definida, en ese sentido es muy similar a una lista o tupla, pero a diferencia de estos, un array solo admite un tipo de dato.

- Consultar documentación: https://numpy.org/

## Crear un array

Un array puede ser creado mediante el uso de datos nativos de python (listas, tuplas,datos
básicos) usando la función **numpy.array()**:

```python
numpy.array(object, dtype=None)
```
Donde podemos especificar el tipo de datos con *dtype*, el orden con *order* (esto hace referencia el modo "C", por filas, o "F", por columnas, para el diseño de memoria del arreglo. Generalmente se deja en "K" para que automaticamente escoja la mejor opción), la dimensión miníma puede establecerse con con *ndmin*.

In [1]:
#import numpy
#import numpy as np
from numpy import array 

In [ ]:
lista_num = [1,2,3,4,5]
array(lista_num, dtype = int)

In [ ]:
lista_num = [1,2,3,4,5, True, False]
array(lista_num)

In [ ]:
lista_num = [1,2,3,4,5, "hola", False]
array(lista_num, dtype = str)

## Arrays de mas de una dimension

Es importante observar que lso arrays pueden tener tanto filas como columnas queramos

In [ ]:
lista_num = [[1,2,3,4,5]]
array(lista_num, dtype = int)

In [ ]:
lista_num = [[1,2,3,4,5], [6,7,8,9,10]]
array_num = array(lista_num, dtype = int)
print(array_num)

In [ ]:
lista_num = [[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]
array_num = array(lista_num, dtype = int)
print(array_num)

In [ ]:
array_num = array([
    [1, 2, 3, 4,  5], 
    [6, 7, 8, 9, 10], 
    [11,12,13,14,15]
], dtype = int)

print(array_num)

## Atributos de un array

Los arrays pueden tener diferentes atributos, estos son algunos de los mas comunes:

- `shape`, `size`, `dtype`, `nbytes`

### Atributo shape

In [ ]:
array_num.shape

In [ ]:
lista_num = [1,2,3,4,5]
x = array(lista_num, dtype = int)
print(x)
x.shape

### Atributo size

In [ ]:
array_num = array([
    [1, 2, 3, 4,  5], 
    [6, 7, 8, 9, 10], 
    [11,12,13,14,15]
], dtype = int)

print(array_num)
array_num.size

### Atributo dtype

In [ ]:
type(array_num)

In [ ]:
array_num.dtype

### Atributo nbytes

In [ ]:
array_num = array([
    [1, 2, 3, 4,  5], 
    [6, 7, 8, 9, 10], 
    [11,12,13,14,15]
], dtype = "U8")

print(array_num)
array_num.size

In [ ]:
array_num.nbytes

In [ ]:
from pandas import read_csv

## Algunos metodos

Los métodos de un array nos permiten realizar algunas de sus funcionalidades como veremos acontinuación:

### Metodo transpose()

In [2]:
array_num = array([
    [1, 2, 3, 4,  5], 
    [6, 7, 8, 9, 10], 
    [11,12,13,14,15]
], dtype = int)
print(array_num)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
print(array_num.transpose())

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [5]:
print(array_num.T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Metodo arange()

In [6]:
from numpy import arange

In [11]:
array_new = arange(1, 100, 34)
print(array_new)

[ 1 35 69]


In [12]:
array_new = arange(start = 1, stop = 100, step = 34)
print(array_new)

[ 1 35 69]


In [14]:
array_new = arange(stop = 100, step = 34, start = 1)
print(array_new)

[ 1 35 69]


In [13]:
array_new = arange(1, 34, 100)
print(array_new)

[1]


### Metodo linspace

In [15]:
from numpy import linspace

In [32]:
array_lp = linspace(start = 0, stop = 100, num = 100)
array_lp

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [33]:
array_lp.size

100

### Metodo random.rand()

In [41]:
from numpy.random import rand, randint

In [36]:
rand(5, 3)

array([[0.90213679, 0.79737709, 0.46640734],
       [0.47701153, 0.56765184, 0.30239441],
       [0.98917359, 0.75022349, 0.55506702],
       [0.62590679, 0.44847375, 0.72307742],
       [0.01494323, 0.78561394, 0.45949059]])

In [37]:
rand(5, 3)*10

array([[1.57013122, 0.58883243, 8.22204054],
       [9.05299839, 7.39228667, 9.37302152],
       [6.29961479, 2.59328059, 2.18941309],
       [4.67654338, 2.18359997, 1.42813835],
       [3.8077165 , 3.3757063 , 2.67964931]])

In [38]:
rand(5, 3)*100

array([[58.90132869, 32.67325649, 46.27833421],
       [96.28113427, 35.75910513, 19.29778202],
       [89.34711337,  0.60548489, 93.31434991],
       [35.30955985, 80.99502688, 78.2846568 ],
       [15.28166094, 61.88454512, 30.93864952]])

### Metodo randint

In [47]:
randint(100, size = (5, 3))

array([[94, 98, 57],
       [68, 55, 63],
       [74,  8, 69],
       [84, 18, 57],
       [78, 52, 54]])

### Metodo ones()

In [49]:
array([1,1,1,1,1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
from numpy import ones, zeros

In [53]:
print(ones(shape = (5,5), dtype = int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Metodo zeros()

In [ ]:
from numpy import zeros

In [55]:
print(zeros(shape = (5,5), dtype = int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Metodo identity()

In [56]:
from numpy import identity

In [59]:
identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Metodo random.uniform()

In [60]:
from numpy.random import uniform

In [66]:
uniform(1, 1000, 100)

array([485.92528941,  56.87772074, 518.73655666, 476.46980875,
       495.60783141, 180.98291039, 407.34688855, 629.43870863,
       306.58222233,  41.54986062, 579.14217707, 952.89682982,
       502.05062882, 802.21139381, 407.23147547, 578.28488913,
       736.89820069, 235.53088089, 459.77231892, 585.09578165,
       305.49963792, 518.05865794, 827.75832703, 305.8918367 ,
       764.70566575,  15.05451202, 221.41723292, 473.41958358,
       325.92053471, 137.23617752, 234.47375098, 579.80426296,
       563.40105791,  58.69031804, 482.64769526, 657.24591496,
       490.64396936, 409.48462063, 969.96060105, 938.03529523,
       324.39979121, 508.14318217, 324.39196871, 963.28714302,
       224.5757092 , 593.13387351, 292.03623764,  48.74080641,
       804.14006594, 679.96267334,  55.07337071, 597.1675178 ,
       218.83754852, 229.78984093,  52.02612599, 271.96780855,
       683.67444412, 995.9103115 , 749.83514544, 690.74443841,
       304.78419156, 692.37584594, 392.27201362, 964.37

### Metodo copy()

In [68]:
x = [1,2,3,4]
y = x

print(f"valores en x: {x}")
print(f"valores en x: {y}")

valores en x: [1, 2, 3, 4]
valores en x: [1, 2, 3, 4]


In [69]:
x.append("Hola")
print(f"valores en x: {x}")

valores en x: [1, 2, 3, 4, 'Hola']


In [70]:
print(f"valores en x: {y}")

valores en x: [1, 2, 3, 4, 'Hola']


In [71]:
## con el metodo copy
x = [1,2,3,4]
y = x.copy()

print(f"valores en x: {x}")
print(f"valores en x: {y}")

valores en x: [1, 2, 3, 4]
valores en x: [1, 2, 3, 4]


In [72]:
x.append("Hola")
print(f"valores en x: {x}")

valores en x: [1, 2, 3, 4, 'Hola']


In [73]:
print(f"valores en y: {y}")

valores en x: [1, 2, 3, 4]


In [84]:
## con arrays
x = array([[1,2,3,4]])
y = x.copy()

print(f"valores en x: {x}, id: {id(x)}")
print(f"valores en y: {y}, id: {id(y)}")

valores en x: [[1 2 3 4]], id: 1900416840496
valores en y: [[1 2 3 4]], id: 1900416840400


In [83]:
## con arrays
x = array([[1,2,3,4]])
y = x

print(f"valores en x: {x}, id: {id(x)}")
print(f"valores en y: {y}, id: {id(y)}")

valores en x: [[1 2 3 4]], id: 1900415939376
valores en y: [[1 2 3 4]], id: 1900415939376
