# Introducción a la programación con Python y Estructuras basicas

Python es un lenguaje de programación de alto nivel (sintaxis simple), interpretado, interactivo y orientado a objetos:

* **Interpretado**: Python es procesado al momento de la ejecución por el interpretador. No se necesita de un proceso previo de compilación para la posterior ejecución del programa.

* **Interactivo**: Podemos interactuar con el intérprete directamente para escribir los programas.

* **Orientado a objetos**: Python es un lenguaje orientado a objetos, una técnica de programación que encapsula el código dentro de objetos.

**Ejecutando código de Python**

Existen diferentes maneras de ejecutar código de Python, ya sea en Visual Studio Code, siendo este uno de los editores de código mas populares y de uso libre, pero en la ciencia de datos resulta siendo más útili utilizar los Notebooks, nosotros usaremos un enfoque interactivo proporcionado por los *Notebooks de Jupyter*. 

## Tipos datos de datos básicos

In [172]:
enteros = 1      
flotantes = 1.0
booleanos = True
booleanos = False
cadenas = "palabra dede"
cadenas = 'palabra dede'

# Palabras claves reservadas

Ahora hablemos de lo que son algunos objetos en python. Las variables.
Los nombres de las variables en Python pueden contener caracteres alfanuméricos *a-z*, *A-Z*, *0-9* y algunos caracteres especiales como _. Los nombres de las variables deben comenzar con una letra. 

Por convención, los nombres de las variables comienzan con letras minúsculas, y los nombres de las Clases con letras mayúsculas.

Adicionalmente, existe un número de palabras claves que no pueden ser usadas como nombres de variables. Estas palabras claves son:

```Python
and, as, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield
```
Las palabras clave se reconocen porque todas se "ponen" de color verde


# Listas

En esta sección se presenta uno de los tipos integrados más útiles de Python, las **listas**.

Al igual que un **string**, una lista es una secuencia de valores. En un string los valores son caracteres; en una **lista**, se puede tener **cualquier tipo**. Los **valores de una lista** se denominan **elementos**.

Hay varias formas de crear una nueva lista; la forma más simple es encerrar los elementos entre corchetes `[a,b,c]`:

In [5]:
listas = [1, 2.5, True, "cadenas", [1, 2, 4]]
listas

[1, 2.5, True, 'cadenas', [1, 2, 4]]

In [6]:
type(listas)

list

# Manipular listas

- Consultar metodos de listas: https://docs.python.org/es/3/tutorial/datastructures.html

Para acceder a los elementos de la lista lo hacemos mediante siguiendo la indexación 

`listas[0]`$\rightarrow$ elemento 1 de la lista.

`listas[1]`$\rightarrow$ elemento 2 de la lista.

`listas[2]`$\rightarrow$ elemento 3 de la lista.

`listas[3]`$\rightarrow$ elemento 4 de la lista.

Acceder a un rango determinado de datos dentro de la lista:

`listas[0:3]`$\rightarrow$ elemento 0 al elemento 3

Acceder al último elemento de lista:

`listas[-1]`$\rightarrow$ elemento final de la lista


In [13]:
listas = [1, 2, 3, 4, 5, 6]
#         0  1  2  3  4  5

listas[0:4]

[1, 2, 3, 4]

In [11]:
listas[5:6]

[6]

In [14]:
listas[-1]

6

In [20]:
listas = [1, 2.5, True, "cadenas", [1, 2, 4]]
listas[-1][-1]

4

In [22]:
listas.append(False)

# Diccionario

Los diccionarios son también parecidos a las listas, excepto que cada elemento es una pareja clave y valor. La sintaxis en los diccionarios es de la forma 

```Python
diccionario = {
    "clave_1" : valor1, 
    "clave_2" : valor2,
         .         .
         .         .
         .         .
         .         .,
    "clave_N" : valorN
}
```

El valor de cada clave puede ser desde un valor numerico hasta datos como listas, arrays y hasta DataFrames

In [7]:
dict_1 = {
    "Ciudades": ["Medellin", "Bogota", "Cali"],
    "Departamentos": ["Antioquia", "Cundinamarca", "Valle"]
}
dict_1

{'Ciudades': ['Medellin', 'Bogota', 'Cali'],
 'Departamentos': ['Antioquia', 'Cundinamarca', 'Valle']}

# Manipular diccionarios

In [24]:
dict_1 = {
    "Ciudades": ["Medellin", "Bogota", "Cali"],
    "Departamentos": ["Antioquia", "Cundinamarca", "Valle"]
}

dict_1

{'Ciudades': ['Medellin', 'Bogota', 'Cali'],
 'Departamentos': ['Antioquia', 'Cundinamarca', 'Valle']}

In [31]:
dict_1["Ciudades"]

['Medellin', 'Bogota', 'Cali']

In [27]:
dict_1.keys()

dict_keys(['Ciudades', 'Departamentos'])

# Estructura if, elif y else

## If
If para python es un condicional. Algunos autores lo llamarán una estructura de control, con lo cual solo quieren ilustrar lo que se ha querido decir en la definición de condicional. Esta estructura permite que un programa ejecute unas instrucciones cuando se cumplan una condición. Es importante notar la palabra "if" en inglés traduce "si" como condición, no "sí" como afirmación.

La sintaxis del condicional if es



```Python
if condición :
    <bloque de codigo a ejecutar si la condicion se cumple>
```


In [43]:
numero = 39
if numero >= 18:        
    print("Mayor de Edad")

Mayor de Edad


## Else
Suponga ahora que se desea ejecutar un bloque de código dado que la condición inicial sea falsa, para esto se usa el comando `else`, el cual se ejecuta siempre y cuando la condición del `if` no se cumpla.

```Python
if cond :
    <bloque de codigo a ejecutar si la condicion se cumple>
else :
    <bloque de codigo a ejecutar si la condicion no se cumple>
```


In [ ]:
numero = 39
if numero >= 18:        
    print("Mayor de Edad")
else:
    print("Menor de edad")

## Elif
Suponga que desea ahora imponer una condición ante la negación de la primera afirmación. Es decir, si la primera primera condición resultó falsa necesito formular otra condición. En este caso usamos el condicional `elif`. Este nace de la conjunción de `else` y `if`. Veamos su sintaxis.

```python
if cond1 :
    <bloque de codigo a ejecutar si la condicion se cumple>
    
elif cond2:
    <bloque de codigo a ejecutar si la condicion del if no se cumple, pero la condicion del elif debe cumplirse> 
```

Veámoslo con nuestro ejemplo.

In [53]:
numero = 60

if numero < 18:
    print("Adolescente")
    
elif (numero >= 18) & (numero <= 59):
    print("Adulto")
    
elif numero >= 60:
    print("Adulto mayor")
    
else:
    print("ingrese un numero valido")

Adulto mayor


# Loops, ciclos o bucles

Hemos visto que un condicional es una decisión sobre una sentencia. Ahora nos ocuparemos de los ciclos. Podríamos pensar que un loop, ciclo o bucle es un bloque que se ejecuta continuamente mientras se cumpla una condición.

## For

El ciclo `for` es el más usual de todos. Su uso es fácil, se llama una variable y se itera en un bloque de código mientras se cumpla dicha condición sumándole cada vez un valor llamado `step`. Es válido notar que el bloque no debe depender de dicha variable o contador.

La sintaxis en Python es la siguiente:

```Python
for contador in range (inicio, fin, step):
    <bloque de código a ejecutar>
```

In [177]:
for i in range(0, 10, 1):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


Cabe resaltar que las listas son elementos que se peuden iterar dentro de un ciclo `for` como veremos a continuación:

el iterador es aquel dato que contiene multiples elementos que podemos utilizar como ietradores del ciclo

```Python
for contador in <iterador>:
    <bloque de código a ejecutar>
```

In [56]:
lista_ciudades = ["Medellin", "Barranquilla", "Manizales"]

for i in lista_ciudades:
    print(i)

Medellin
Barranquilla
Manizales


Pdemos tener además tener un `for` dentro de otro `for`, de la siguiente forma

In [60]:
for i in range(0, 1):
    for j in range(0, 1):
        print(j)

0


# Modulo Numpy

Numpy es un paquete fundamental para el trabajo científico en python:
* Contiene Funciones, módulos, clases y cierto tipo especial de datos. 
* Permite el manejo de Arrays Multidimensionales. 
* Contiene Funciones sofisticadas y optimizadas. Permite incorporar códigos en C/C++ o fortran. 
* Contiene un paquete de álgebra lineal y permite hacer cálculos estadísticos, ajustes, interpolación entre otras.


> El tipo de dato mas importante en numpy es el **array**. El array es un tipo de dato, formado a partir de otro tipo de datos mas sencillos y que estan ordenados en una secuencia definida, en ese sentido es muy similar a una lista o tupla, pero a diferencia de estos, un array solo admite un tipo de dato.

- Consultar documentación: https://numpy.org/doc/stable/reference/arrays.html#

In [64]:
import numpy as np

## Crear un array

Un array puede ser creado mediante el uso de datos nativos de python (listas, tuplas,datos
básicos) usando la función **numpy.array()**:

```python
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```
Donde podemos especificar el tipo de datos con *dtype*, el orden con *order* (esto hace referencia el modo "C", por filas, o "F", por columnas, para el diseño de memoria del arreglo. Generalmente se deja en "K" para que automaticamente escoja la mejor opción), la dimensión miníma puede establecerse con con *ndmin*.

## Crear un numpy array

In [81]:
lista_num = [1, 2, 3, 4, 5, 6, "7"]
print(lista_num)

[1, 2, 3, 4, 5, 6, '7']


In [83]:
arreglo = np.array(lista_num)
arreglo

array(['1', '2', '3', '4', '5', '6', '7'], dtype='<U1')

In [72]:
print(arreglo)

[1 2 3 4 5]


In [76]:
arreglo = np.array(lista_num, dtype = float)
print(arreglo)

[1. 2. 3. 4. 5.]


In [84]:
arreglo_bool = np.array([True, False, True])
arreglo_bool

array([ True, False,  True])

## Arrays de mas de una dimension

Es importante observar que lso arrays pueden tener tanto filas como columnas queramos

In [178]:
lista_num = [[0, 1], [2, 3], [4, 5]]

arreglo_2 = np.array(lista_num)
arreglo_2

array([[0, 1],
       [2, 3],
       [4, 5]])

Observe que si intenta crear un array donde una de las filas contiene mas columnas que las demas el array no podrá crearse correctamente

In [96]:
lista_num = [[0, 1], [2, 3, 6], [4, 5]]

arreglo_2 = np.array(lista_num)
arreglo_2

C:\Users\DavidPiedrahitaFlore\.conda\envs\renting_env\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


array([list([0, 1]), list([2, 3, 6]), list([4, 5])], dtype=object)

# Atributos de un array

Los arrays pueden tener diferentes atributos, estos son algunos de los mas comunes:

- `shape`, `size`, `dtype`, `nbytes`

## Tamaño de un Array

In [99]:
arreglo_2.shape

(3, 2)

## Numero de elementos del array

In [101]:
arreglo_2.size

6

## Tipo de datos dentro del array

In [103]:
arreglo_2.dtype

dtype('int32')

## Tamaño en bytes

In [104]:
arreglo_2.nbytes

24

## Transpuesta de un array

In [106]:
arreglo_2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [105]:
arreglo_2.T

array([[0, 2, 4],
       [1, 3, 5]])

# Algunos métodos de numpy

Los métodos de un array nos permiten realizar algunas de sus funcionalidades como veremos acontinuación:

## np.arange()

In [107]:
# np.arange([start], [stop], [step])

arreglo_range_1 = np.arange(0, 20)
arreglo_range_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [140]:
arreglo_range_2 = np.arange(start = 0, stop = 20, step = 2)
arreglo_range_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arreglo_range_3 = np.arange(0, 20, 2)
arreglo_range_3

## np.linspace

In [120]:
# np.linspace(start, stop, num = 50)

arreglo_linspace = np.linspace(0, 50, num = 10)
arreglo_linspace

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [116]:
arreglo_linspace.size

50

## np.random.rand()

In [134]:
# np.random.rand(rows, columns) me crea una arreglo de nxm con numeros aleatorios entre 0 y 1
arreglo_random = np.random.rand(5, 2)
arreglo_random

array([[0.47328337, 0.55203513],
       [0.09258403, 0.20004293],
       [0.59383189, 0.86727883],
       [0.74756399, 0.01783241],
       [0.06235529, 0.27282839]])

## Crear arreglos de unos y ceros

In [137]:
unos = np.ones((5, 5), dtype = int)
unos

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [139]:
ceros = np.zeros(shape = (5, 5), dtype = int)
ceros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## numpy.random.uniform()

In [150]:
arreglo_uniform = np.random.uniform(50, 55, 10)
arreglo_uniform

array([50.49274091, 52.93309988, 52.71488789, 53.34824206, 54.83992339,
       54.42319673, 53.13623221, 50.57043238, 50.79146487, 54.10761278])

## array metodo copy()

### tener en cuenta:

In [151]:
lista = [1,2,3,4]
lista_2 = lista

In [152]:
lista

[1, 2, 3, 4]

In [153]:
lista_2

[1, 2, 3, 4]

In [154]:
lista.append(5)
lista

[1, 2, 3, 4, 5]

In [155]:
lista_2

[1, 2, 3, 4, 5]

In [156]:
lista_new = [1,2,3,4,5]
lista_new_2 = lista_new.copy()

In [157]:
lista_new.append(3)
lista_new

[1, 2, 3, 4, 5, 3]

In [158]:
lista_new_2

[1, 2, 3, 4, 5]

## En el caso de los array

In [160]:
arreglo_uniform = np.random.uniform(50, 55, 10)
arreglo_uniform

array([50.42193755, 50.8067939 , 51.19831565, 53.15880655, 51.57721772,
       51.94305718, 53.7060828 , 52.15830396, 54.65960883, 51.44651319])

In [161]:
arreglo_uniform_copia = arreglo_uniform.copy()
arreglo_uniform_copia

array([50.42193755, 50.8067939 , 51.19831565, 53.15880655, 51.57721772,
       51.94305718, 53.7060828 , 52.15830396, 54.65960883, 51.44651319])

In [162]:
arreglo_uniform = arreglo_uniform*10
arreglo_uniform

array([504.21937546, 508.06793897, 511.98315651, 531.58806552,
       515.77217717, 519.43057183, 537.06082798, 521.58303962,
       546.59608827, 514.46513194])

In [163]:
arreglo_uniform_copia

array([50.42193755, 50.8067939 , 51.19831565, 53.15880655, 51.57721772,
       51.94305718, 53.7060828 , 52.15830396, 54.65960883, 51.44651319])

# Definicion de funciones

# Funciones
Usualmente en el desarrollo de un código debemos usar varias veces el mismo algoritmo, no necesariamente de forma periódica. Es fácil pensar que si quiero calcular un valor estadístico que no esté predefinido por algo el lenguaje de programación, tendremos que ir haciendo `Ctrl+C` y luego `Ctrl+V` del código como tantas veces lo necesitemos por todo nuestro código. Para evitar esto existen las funciones. Con ellas es posible desarrollar de forma ordenada el código y por consiguiente más entendible.

La sintaxis de una función es la siguiente:

```Python
def Nombre_de_la_funcion(arg1, arg2,...argn):
    bloque de código
    return valor_a_retornar #------> solo si se necesita que la funcion retorne un valor


# si no es necesario retornar un valor se puede escrbir así:
def nombre_funcion(arg1, arg2,...argn):
    bloque de código                    
```
En general es necesario el uso de `return` al final de cada función. De esa forma la función sabe exactamente qué debe devolver. 


In [164]:
def sumar_dos_numeros(num1, num2):
    print(num1 + num2)

In [165]:
sumar_dos_numeros(24, 10)

34


In [166]:
def resta_dos_numeros(num1, num2):
    resta = num1 - num2
    return resta

In [170]:
x = resta_dos_numeros(3, 4545)

In [171]:
x

-4542

# Ejercicios propuestos

**Ejercicio 1**

Determine para un número entero cualquiera si es par o impar
- Utilice una sentencia if - else

In [2]:
num = 21

if num % 2 == 0:
    print("El numero es par")
else:
    print("El numero es impar")

El numero es impar


**Ejercicio 2**:

Determine de un número cualquiera real entero positivo si es un número primo o no
- Tip: utilice un ciclo for para realizar dicha operación

In [4]:
x = 11
primo = 0
prueba = 0
for i in range(2,x):
    prueba = x % i
    if prueba == 0:
        primo = primo +1

if primo == 0:
    print(str(x) + " es primo")
else:
    print(str(x) + " no es primo")

11 es primo


**Ejercicio 3**:

Cree una lista con cualquier tipo de dato del tamaño que usted considere, a dicha lista agregue un dato utilizando el método append

In [5]:
lista = [1, 2, 3, 4, 5]
lista.append("Python")
lista

[1, 2, 3, 4, 5, 'Python']

**Ejercicio 4**:

Cree una lista con cualquier tipo de dato del tamaño que usted considere, a dicha lista elimine un dato utilizando algún método que permita hacerlo, consulte en el siguiente link los diferentes métodos asociados a las listas y busque el método apropiado:
- Métodos de las listas: https://docs.python.org/es/3/tutorial/datastructures.html

In [6]:
lista = [1, 2, 3, 4, 5, "Python"]
lista.remove("Python")
lista

[1, 2, 3, 4, 5]

**Ejercicio 5:**

En un colegio personalizado del país, se tienen salones constituidos por 5 estudiantes. La lista de estudiantes de uno de ellos es:

```
kinderA_lista = ['Gómez, Sebastián', 'Arango, Natalia', 'Zambrano, Javier', 'Domingo, Carolina'] 
````

Organice dicha lista en orden alfabético, guardándola en la misma variable e imprímala en pantalla.

- tip: para resolver este ejercicio consulte de nuevo los métodos de las listas, allí encontrará un método que permita ordenar la lista

In [7]:
kinderA_lista = ['Gómez, Sebastián', 'Arango, Natalia', 'Zambrano, Javier', 'Domingo, Carolina']
kinderA_lista.sort()
kinderA_lista

['Arango, Natalia',
 'Domingo, Carolina',
 'Gómez, Sebastián',
 'Zambrano, Javier']

**Ejercicio 6:** 

La siguiente lista representa una pequeña base de datos constituida por pacientes de una clinica en la ciudad de Medellín. Cada paciente se identifica como:

```
ID_numero-Medellin
```
Por motivos de optimización, un programador en `python`requier extraer solamente el número de identificación de cada elemento de la lista. Realice la extracción del número elemento por elemento, de la siguiente lista:

```
pacientes = ["ID_0001-Medellin","ID_0002-Medellin","ID_0003-Medellin","ID_0004-Medellin"]
```

- tip: consulte la documentación del método split para dar solución al ejercicio: https://python-reference.readthedocs.io/en/latest/docs/str/split.html

In [8]:
pacientes = ["ID_0001-Medellin","ID_0002-Medellin","ID_0003-Medellin","ID_0004-Medellin"]

pacientes[0] = pacientes[0].split('-')[0].split('_')[1]
pacientes[1] = pacientes[1].split('-')[0].split('_')[1]  
pacientes[2] = pacientes[2].split('-')[0].split('_')[1] 
pacientes[3] = pacientes[3].split('-')[0].split('_')[1] 
pacientes

['0001', '0002', '0003', '0004']

**Ejercicio 7:**

Escriba un programa que permita calcular la suma de los 100 primeros números.

- tip: utilice un ciclo for para resolver el ejercicio, además consulte como utilizar un contador dentro de un ciclo

In [9]:
suma = 0

for i in range(101):
    suma = suma + i

print(suma)

5050


**Ejercicio 8:**

En matemáticas, la sucesión o serie de Fibonacci hace referencia a la secuencia ordenada de números descrita por Leonardo de Pisa, matemático italiano del siglo XIII:

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144,…]

A cada uno de los elementos de la serie se le conoce con el nombre de número de Fibonacci.

Realice un programa que permita calcular una lista que contenga la serie fibonacci hasta la posición 20 así:

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]

- Para calcular el siguiente número de la serie `numero(k+1) = numero(k-1) + numero(k)`

- tip: utilice un ciclo for e inicialice una lista con los siguientes números [0, 1] antes de ejecutar el for

In [ ]:
fibo = [0]*2
fibo[0] = 0
fibo[1] = 1

for i in range(2, 21):
    fibo.append(fibo[i-1] + fibo[i-2])
    
print(fibo)

**Ejercicio 9:** 

Cree una función que solicite al usuario una palabra e imprima si esta es un palíndromo o no. (Un palíndromo es una palabra o frase que se lee igual hacia adelante y hacia atrás), por ejemplo:

- Anilina, note que la palabra al leerla de izuqierda a derecha y de derecha a izquierda es exactamante igual

- tip: para resolver el ejercicio consulte como invertir una cadena de caracteres


In [3]:
def palindromo(palabra):
    palabra = palabra.replace(' ', '')
    palabra = palabra.lower()
    palabra_invertida = palabra[::-1]
    if palabra == palabra_invertida:
        return True
    else:
        return False

palabra = "Anilina"
palabra = "Ana"
palabra = "Acá"
es_palindromo = palindromo(palabra)

if es_palindromo == True:
    print(palabra + " es un palindromo")
else:
    print(palabra + " no es un palindromo")

Acá no es un palindromo
